### ISSUE TITLE
install of all will not work

### ISSUE THREAD

**Issue by digitaltvguy** [Bl4Cc4t/homebrew-vsplugins#1]
**HEAD is now at 2fb3503 Add Meson build system**
==> ./configure --install=/usr/local/Cellar/vsp-addgrain/HEAD-2fb3503/lib
Last 15 lines from /Users/cseeger/Library/Logs/Homebrew/vsp-addgrain/01.configure:
2018-12-28 12:35:33 -0500

./configure
--install=/usr/local/Cellar/vsp-addgrain/HEAD-2fb3503/lib

**Comment by Bl4Cc4t** [comment]
@digitaltvguy I updated the Formulae, everything should install properly now.

**Comment by digitaltvguy** [comment]
Thank you.

**Comment by Bl4Cc4t** [comment]
sure thing :)
